-- テーブル作成
create table heartbeats (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  source text not null
);

-- 権限設定（デモ用：誰でも読み書きOK）
alter table heartbeats enable row level security;
create policy "Enable read access for all users" on heartbeats for select using (true);
create policy "Enable insert access for all users" on heartbeats for insert with check (true);
